### ISSUE TITLE
Library incompatible w/ latest apache-libcloud

### ISSUE THREAD

**Issue by mattt416** [racker/rackspace-monitoring#53]
Hi All,

I have some nodes w/ apache-libcloud==2.0.0rc2 installed which seems to break rackspace-monitoring:

```
>>> import ConfigParser
>>> cfg = ConfigParser.RawConfigParser()
>>> cfg.read('/root/.raxrc')
['/root/.raxrc']
>>> ['/root/.raxrc']
['/root/.raxrc']
>>> from rackspace_monitoring.providers import get_driver
>>> from rackspace_monitoring.types import Provider
>>> driver = get_driver(Provider.RACKSPACE)
>>> conn = driver(cfg.get('credentials', 'username'), cfg.get('credentials', 'api_key'))
>>> conn.list_entities()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/openstack/venvs/maas-r13.1.0rc1/local/lib/python2.7/site-packages/libcloud/common/types.py", line 132, in __repr__
    self._load_all()
  File "/openstack/venvs/maas-r13.1.0rc1/local/lib/python2.7/site-packages/libcloud/common/types.py", line 141, in _load_all
    value_dict=self._value_dict)
  File "rackspace_monitoring/drivers/rackspace.py", line 233, in _get_more
    response = self.connection.request(value_dict['url'], params)
  File "rackspace_monitoring/drivers/rackspace.py", line 152, in request
    raw=raw
  File "/openstack/venvs/maas-r13.1.0rc1/local/lib/python2.7/site-packages/libcloud/common/openstack.py", line 227, in request
    raw=raw)
  File "/openstack/venvs/maas-r13.1.0rc1/local/lib/python2.7/site-packages/libcloud/common/base.py", line 607, in request
    headers=headers, stream=stream)
  File "/openstack/venvs/maas-r13.1.0rc1/local/lib/python2.7/site-packages/libcloud/httplib_ssl.py", line 211, in request
    verify=self.verification
  File "/openstack/venvs/maas-r13.1.0rc1/local/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/openstack/venvs/maas-r13.1.0rc1/local/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/openstack/venvs/maas-r13.1.0rc1/local/lib/python2.7/site-packages/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='127.0.0.1', port=443): Max retries exceeded with url: /v1.0/redacted/entities (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fad79acf590>: Failed to establish a new connection: [Errno 111] Connection refused',))
>>>
```

The issue seems related to this: https://issues.apache.org/jira/browse/LIBCLOUD-904

Perhaps rackspace-monitoring should install a version of apache-libcloud that's < 2?

Thanks!

--Matt

**Comment by hughsaunders** [comment]
Confirmed, after installing rackspace-monitoring-cli in a clean venv, the commands fail:

```
(raxmon) hughs-mbp:UG-618 hughsaunders$ raxmon-entities-list
Traceback (most recent call last):
  File "/Users/hughsaunders/Documents/context/UG-618/raxmon/bin/raxmon-entities-list", line 18, in <module>
    from raxmon_cli.common import run_action
  File "/Users/hughsaunders/Documents/context/UG-618/raxmon/lib/python2.7/site-packages/raxmon_cli/common.py", line 35, in <module>
    libcloud.security.CA_CERTS_PATH.insert(0, CA_CERT_PATH)
AttributeError: 'str' object has no attribute 'insert'
```

manually installing apache-libcloud<2.0 fixes the problem.
